# Generated by Django 5.1.1 on 2024-09-28 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmediafile",
            name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="uploaded_at",
        ),
    ]
