# Generated by Django 5.1.1 on 2024-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_remove_historicalmediafile_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmediafile",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
